FROM node:14-alpine as build
WORKDIR /admin
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
WORKDIR /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /admin/build ./admin

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]